

POST http://localhost:9000/api/v1/contract-service/create
content-type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hbnVlbCBQZWRybyIsInN1YiI6IjI3MTZhODgwLTJlNDItNDc3Mi1hNjZkLTRlMGU0NmViYjE1MCIsImlhdCI6MTcyMTc3OTY5OSwiZXhwIjoxNzIyMzg0NDk5fQ.vhfqELUXQpVC5LcwaeNW0ZGkZr_4REFF4yB8mnuj_yM

{
  
    "serviceId": "9ac30138-5384-475d-b32b-eec0235ce74b"
}


###
GET  http://localhost:9000/api/v1/contract-services/9e05dd09-cd63-4b10-a4de-5e7146d6c1b9
content-type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hbnVlbCBQZWRybyIsInN1YiI6IjI3MTZhODgwLTJlNDItNDc3Mi1hNjZkLTRlMGU0NmViYjE1MCIsImlhdCI6MTcyMTc3OTY5OSwiZXhwIjoxNzIyMzg0NDk5fQ.vhfqELUXQpVC5LcwaeNW0ZGkZr_4REFF4yB8mnuj_yM


###

GET  http://localhost:9000/api/v1/contract-service
content-type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hbnVlbCBQZWRybyIsInN1YiI6IjI3MTZhODgwLTJlNDItNDc3Mi1hNjZkLTRlMGU0NmViYjE1MCIsImlhdCI6MTcyMTc3OTY5OSwiZXhwIjoxNzIyMzg0NDk5fQ.vhfqELUXQpVC5LcwaeNW0ZGkZr_4REFF4yB8mnuj_yM


###

PUT  http://localhost:9000/api/v1/contract-services/9e05dd09-cd63-4b10-a4de-5e7146d6c1b9
content-type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hbnVlbCBQZWRybyIsInN1YiI6IjI3MTZhODgwLTJlNDItNDc3Mi1hNjZkLTRlMGU0NmViYjE1MCIsImlhdCI6MTcyMTc3OTY5OSwiZXhwIjoxNzIyMzg0NDk5fQ.vhfqELUXQpVC5LcwaeNW0ZGkZr_4REFF4yB8mnuj_yM

{
  
    "serviceId": "9ac30138-5384-475d-b32b-eec0235ce74b"
}


###

DELETE   http://localhost:9000/api/v1/contract-service/9e05dd09-cd63-4b10-a4de-5e7146d6c1b9
content-type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hbnVlbCBQZWRybyIsInN1YiI6IjI3MTZhODgwLTJlNDItNDc3Mi1hNjZkLTRlMGU0NmViYjE1MCIsImlhdCI6MTcyMTc3OTY5OSwiZXhwIjoxNzIyMzg0NDk5fQ.vhfqELUXQpVC5LcwaeNW0ZGkZr_4REFF4yB8mnuj_yM
